import * as dotenv from 'dotenv';
import * as Joi from 'joi';

dotenv.config({
  path:
    process.env.NODE_ENV === 'production'
      ? '.env.production'
      : '.env.development',
});

interface EnvironmentVariables {
  NODE_ENV: 'development' | 'production' | 'test' | 'provision';
  PORT_DEVELOPMENT: number;
  PORT_PRODUCTION: number;
  AUTH_MICROSERVICE_HOST: string;
  AUTH_MICROSERVICE_PORT: number;
  AUTH_SERVICE: string;
  QR_CODE_MICROSERVICE_HOST: string;
  QR_CODE_MICROSERVICE_PORT: number;
  QR_CODE_SERVICE: string;
  READINGS_MICROSERVICE_HOST: string;
  READINGS_MICROSERVICE_PORT: number;
  READINGS_SERVICE: string;
  KAFKA_BROKER_URL: string;
  AUTH_KAFKA_CLIENT_ID: string;
  AUTH_KAFKA_GROUP_ID: string;
  AUTH_KAFKA_CLIENT: string;
  QRCODE_KAFKA_CLIENT_ID: string;
  QRCODE_KAFKA_GROUP_ID: string;
  QRCODE_KAFKA_CLIENT: string;
  READINGS_KAFKA_CLIENT_ID: string;
  READINGS_KAFKA_GROUP_ID: string;
  READINGS_KAFKA_CLIENT: string;
  QRCODE_SCANNER_KAFKA_GROUP_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_CLIENT: string;
  OBSERVATION_KAFKA_GROUP_ID: string;
  OBSERVATION_KAFKA_CLIENT: string;
  OBSERVATION_KAFKA_CLIENT_ID: string;
  PHOTO_READING_KAFKA_GROUP_ID: string;
  PHOTO_READING_KAFKA_CLIENT: string;
  PHOTO_READING_KAFKA_CLIENT_ID: string;
  LOCATION_CONNECTION_KAFKA_CLIENT_ID: string;
  LOCATION_CONNECTION_KAFKA_GROUP_ID: string;
  LOCATION_CONNECTION_KAFKA_CLIENT: string;
  LOCATION_KAFKA_CLIENT_ID: string;
  LOCATION_KAFKA_GROUP_ID: string;
  LOCATION_KAFKA_CLIENT: string;
  CLIENTS_KAFKA_CLIENT_ID: string;
  CLIENTS_KAFKA_GROUP_ID: string;
  CLIENTS_KAFKA_CLIENT: string;
  COMPANIES_KAFKA_GROUP_ID: string;
  COMPANIES_KAFKA_CLIENT: string;
  COMPANIES_KAFKA_CLIENT_ID: string;
  CONNECTION_KAFKA_GROUP_ID: string;
  CONNECTION_KAFKA_CLIENT: string;
  CONNECTION_KAFKA_CLIENT_ID: string;
  PROPERTY_KAFKA_GROUP_ID: string;
  PROPERTY_KAFKA_CLIENT: string;
  PROPERTY_KAFKA_CLIENT_ID: string;
  OBSERVATION_CONNECTION_KAFKA_GROUP_ID: string;
  OBSERVATION_CONNECTION_KAFKA_CLIENT: string;
  OBSERVATION_CONNECTION_KAFKA_CLIENT_ID: string;
  PHOTO_CONNECTION_KAFKA_GROUP_ID: string;
  PHOTO_CONNECTION_KAFKA_CLIENT: string;
  PHOTO_CONNECTION_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_KAFKA_CLIENT: string;
  GATEWAY_WORK_ORDER_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_KAFKA_GROUP_ID: string;
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT: string;
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_GROUP_ID: string;
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT: string;
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_GROUP_ID: string;
  GATEWAY_WORK_TYPE_KAFKA_CLIENT: string;
  GATEWAY_WORK_TYPE_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_TYPE_KAFKA_GROUP_ID: string;
  GATEWAY_WORKERS_KAFKA_GROUP_ID: string;
  GATEWAY_WORKERS_KAFKA_CLIENT: string;
  GATEWAY_WORKERS_KAFKA_CLIENT_ID: string;
  INVENTORY_KAFKA_CLIENT_ID: string;
  INVENTORY_KAFKA_GROUP_ID: string;
  INVENTORY_KAFKA_CLIENT: string;
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_GROUP_ID: string;
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT: string;
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_GROUP_ID: string;
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT: string;
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT_ID: string;
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_GROUP_ID: string;
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT: string;
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT_ID: string;
  FILE_STORAGE_PATH: string;
  // Auth kafka clients
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT: string;
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT_ID: string;
  GATEWAY_AUTHENTICATION_KAFKA_GROUP_ID: string;
  // Roles kafka clients
  GATEWAY_ROLES_KAFKA_CLIENT: string;
  GATEWAY_ROLES_KAFKA_CLIENT_ID: string;
  GATEWAY_ROLES_KAFKA_GROUP_ID: string;
  // Categories kafka clients
  GATEWAY_CATEGORIES_KAFKA_CLIENT: string;
  GATEWAY_CATEGORIES_KAFKA_CLIENT_ID: string;
  GATEWAY_CATEGORIES_KAFKA_GROUP_ID: string;
  // Permissions kafka clients
  GATEWAY_PERMISSIONS_KAFKA_CLIENT: string;
  GATEWAY_PERMISSIONS_KAFKA_CLIENT_ID: string;
  GATEWAY_PERMISSIONS_KAFKA_GROUP_ID: string;
  // Rol -Permission kafka clients
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT: string;
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT_ID: string;
  GATEWAY_ROL_PERMISSION_KAFKA_GROUP_ID: string;
  // Users kafka clients
  GATEWAY_USERS_KAFKA_CLIENT: string;
  GATEWAY_USERS_KAFKA_CLIENT_ID: string;
  GATEWAY_USERS_KAFKA_GROUP_ID: string;

  // Employees kafka clients
  GATEWAY_EMPLOYEES_KAFKA_CLIENT: string;
  GATEWAY_EMPLOYEES_KAFKA_CLIENT_ID: string;
  GATEWAY_EMPLOYEES_KAFKA_GROUP_ID: string;

  // Auth Kafka clients
  GATEWAY_AUTH_KAFKA_CLIENT: string;
  GATEWAY_AUTH_KAFKA_CLIENT_ID: string;
  GATEWAY_AUTH_KAFKA_GROUP_ID: string;

  // Location Kafka clients
  GATEWAY_LOCATION_KAFKA_CLIENT: string;
  GATEWAY_LOCATION_KAFKA_CLIENT_ID: string;
  GATEWAY_LOCATION_KAFKA_GROUP_ID: string;

  // Trash Rate Kafka clients
  TRASH_RATE_KAFKA_CLIENT_ID: string;
  TRASH_RATE_KAFKA_CLIENT: string;
  TRASH_RATE_KAFKA_GROUP_ID: string;

  // Documents Service Kafka clients
  GATEWAY_DOCUMENTS_KAFKA_CLIENT: string;
  GATEWAY_DOCUMENTS_KAFKA_CLIENT_ID: string;
  GATEWAY_DOCUMENTS_KAFKA_GROUP_ID: string;
  CONNECTION_DOCUMENTS_UPLOAD_DIR: string;

  JWT_SECRET: string;
  JWT_ACCESS_TOKEN_SECRET: string;
  JWT_ACCESS_EXPIRATION: string;
  JWT_REFRESH_EXPIRATION: string;
}

const envVarsSchema: Joi.ObjectSchema<EnvironmentVariables> = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test', 'provision')
    .default('development'),
  PORT_DEVELOPMENT: Joi.number(),
  PORT_PRODUCTION: Joi.number(),
  AUTH_MICROSERVICE_HOST: Joi.string(),
  AUTH_MICROSERVICE_PORT: Joi.number(),
  AUTH_SERVICE: Joi.string(),
  QR_CODE_MICROSERVICE_HOST: Joi.string(),
  QR_CODE_MICROSERVICE_PORT: Joi.number(),
  QR_CODE_SERVICE: Joi.string(),
  READINGS_MICROSERVICE_HOST: Joi.string(),
  READINGS_MICROSERVICE_PORT: Joi.number(),
  READINGS_SERVICE: Joi.string(),
  KAFKA_BROKER_URL: Joi.string(),
  AUTH_KAFKA_CLIENT_ID: Joi.string(),
  AUTH_KAFKA_GROUP_ID: Joi.string(),
  AUTH_KAFKA_CLIENT: Joi.string(),
  QRCODE_KAFKA_CLIENT_ID: Joi.string(),
  QRCODE_KAFKA_GROUP_ID: Joi.string(),
  QRCODE_KAFKA_CLIENT: Joi.string(),
  READINGS_KAFKA_CLIENT_ID: Joi.string(),
  READINGS_KAFKA_GROUP_ID: Joi.string(),
  READINGS_KAFKA_CLIENT: Joi.string(),
  QRCODE_SCANNER_KAFKA_GROUP_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_CLIENT: Joi.string(),
  OBSERVATION_KAFKA_GROUP_ID: Joi.string(),
  OBSERVATION_KAFKA_CLIENT: Joi.string(),
  OBSERVATION_KAFKA_CLIENT_ID: Joi.string(),
  PHOTO_READING_KAFKA_GROUP_ID: Joi.string(),
  PHOTO_READING_KAFKA_CLIENT: Joi.string(),
  PHOTO_READING_KAFKA_CLIENT_ID: Joi.string(),
  LOCATION_CONNECTION_KAFKA_CLIENT_ID: Joi.string(),
  LOCATION_CONNECTION_KAFKA_GROUP_ID: Joi.string(),
  LOCATION_CONNECTION_KAFKA_CLIENT: Joi.string(),
  CLIENTS_KAFKA_CLIENT_ID: Joi.string(),
  CLIENTS_KAFKA_GROUP_ID: Joi.string(),
  CLIENTS_KAFKA_CLIENT: Joi.string(),
  COMPANIES_KAFKA_GROUP_ID: Joi.string().default('companies-group'),
  COMPANIES_KAFKA_CLIENT: Joi.string().default('COMPANIES_KAFKA_CLIENT'),
  COMPANIES_KAFKA_CLIENT_ID: Joi.string().default('companies-client'),
  CONNECTION_KAFKA_GROUP_ID: Joi.string(),
  CONNECTION_KAFKA_CLIENT: Joi.string(),
  CONNECTION_KAFKA_CLIENT_ID: Joi.string(),
  PROPERTY_KAFKA_GROUP_ID: Joi.string(),
  PROPERTY_KAFKA_CLIENT: Joi.string(),
  PROPERTY_KAFKA_CLIENT_ID: Joi.string(),
  OBSERVATION_CONNECTION_KAFKA_GROUP_ID: Joi.string(),
  OBSERVATION_CONNECTION_KAFKA_CLIENT: Joi.string(),
  OBSERVATION_CONNECTION_KAFKA_CLIENT_ID: Joi.string(),
  PHOTO_CONNECTION_KAFKA_GROUP_ID: Joi.string(),
  PHOTO_CONNECTION_KAFKA_CLIENT: Joi.string(),
  PHOTO_CONNECTION_KAFKA_CLIENT_ID: Joi.string(),
  // work orders kafka clients
  GATEWAY_WORK_ORDER_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_ORDER_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_WORK_ORDER_KAFKA_GROUP_ID: Joi.string().required(),
  // history kafka client
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_GROUP_ID: Joi.string().required(),
  // observation kafka client
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_GROUP_ID: Joi.string().required(),
  // type kafka client
  GATEWAY_WORK_TYPE_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_TYPE_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_WORK_TYPE_KAFKA_GROUP_ID: Joi.string().required(),
  // workers kafka client
  GATEWAY_WORKERS_KAFKA_GROUP_ID: Joi.string().required(),
  GATEWAY_WORKERS_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORKERS_KAFKA_CLIENT_ID: Joi.string().required(),
  // inventory kafka client
  INVENTORY_KAFKA_CLIENT_ID: Joi.string().required(),
  INVENTORY_KAFKA_GROUP_ID: Joi.string().required(),
  INVENTORY_KAFKA_CLIENT: Joi.string().required(),
  // detail work order material kafka client
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_GROUP_ID: Joi.string().required(),
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT_ID: Joi.string().required(),
  // work-order-worker-assignment kafka client
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_GROUP_ID: Joi.string().required(),
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT_ID: Joi.string().required(),
  // work-order-attachments kafka client
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_GROUP_ID: Joi.string().required(),
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT_ID: Joi.string().required(),
  // Auth kafka clients
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_AUTHENTICATION_KAFKA_GROUP_ID: Joi.string().required(),
  // Roles kafka clients
  GATEWAY_ROLES_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_ROLES_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_ROLES_KAFKA_GROUP_ID: Joi.string().required(),
  // Categories kafka clients
  GATEWAY_CATEGORIES_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_CATEGORIES_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_CATEGORIES_KAFKA_GROUP_ID: Joi.string().required(),
  // Permissions kafka clients
  GATEWAY_PERMISSIONS_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_PERMISSIONS_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_PERMISSIONS_KAFKA_GROUP_ID: Joi.string().required(),
  // Rol -Permission kafka clients
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_ROL_PERMISSION_KAFKA_GROUP_ID: Joi.string().required(),
  // Users kafka clients
  GATEWAY_USERS_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_USERS_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_USERS_KAFKA_GROUP_ID: Joi.string().required(),
  // Employees kafka clients
  GATEWAY_EMPLOYEES_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_EMPLOYEES_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_EMPLOYEES_KAFKA_GROUP_ID: Joi.string().required(),
  // Auth Kafka clients
  GATEWAY_AUTH_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_AUTH_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_AUTH_KAFKA_GROUP_ID: Joi.string().required(),
  // Location Kafka clients
  GATEWAY_LOCATION_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_LOCATION_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_LOCATION_KAFKA_GROUP_ID: Joi.string().required(),

  // Trash Rate Kafka clients
  TRASH_RATE_KAFKA_CLIENT_ID: Joi.string().required(),
  TRASH_RATE_KAFKA_CLIENT: Joi.string().required(),
  TRASH_RATE_KAFKA_GROUP_ID: Joi.string().required(),

  // Documents Service Kafka clients
  GATEWAY_DOCUMENTS_KAFKA_CLIENT: Joi.string().required(),
  GATEWAY_DOCUMENTS_KAFKA_CLIENT_ID: Joi.string().required(),
  GATEWAY_DOCUMENTS_KAFKA_GROUP_ID: Joi.string().required(),
  CONNECTION_DOCUMENTS_UPLOAD_DIR: Joi.string().optional().default('/home/sigepaa/sigepaa/documents/connection-documents'),

  JWT_SECRET: Joi.string().required(),
  JWT_ACCESS_TOKEN_SECRET: Joi.string().optional(),
  JWT_ACCESS_EXPIRATION: Joi.string().required(),
  JWT_REFRESH_EXPIRATION: Joi.string().required(),
  FILE_STORAGE_PATH: Joi.string().required(),
}).unknown();

const { error, value: envVars } = envVarsSchema.validate(process.env);

if (error) {
  throw new Error(`Config validation error: ${error.message}`);
}

export const environments = {
  NODE_ENV: envVars.NODE_ENV,
  PORT:
    envVars.NODE_ENV === 'production'
      ? envVars.PORT_PRODUCTION
      : envVars.PORT_DEVELOPMENT,
  AUTH_MICROSERVICE_HOST: envVars.AUTH_MICROSERVICE_HOST,
  AUTH_MICROSERVICE_PORT: envVars.AUTH_MICROSERVICE_PORT,
  AUTH_SERVICE: envVars.AUTH_SERVICE,
  QR_CODE_MICROSERVICE_HOST: envVars.QR_CODE_MICROSERVICE_HOST,
  QR_CODE_MICROSERVICE_PORT: envVars.QR_CODE_MICROSERVICE_PORT,
  QR_CODE_SERVICE: envVars.QR_CODE_SERVICE,
  READINGS_MICROSERVICE_HOST: envVars.READINGS_MICROSERVICE_HOST,
  READINGS_MICROSERVICE_PORT: envVars.READINGS_MICROSERVICE_PORT,
  READINGS_SERVICE: envVars.READINGS_SERVICE,
  KAFKA_BROKER_URL: envVars.KAFKA_BROKER_URL,
  AUTH_KAFKA_CLIENT_ID: envVars.AUTH_KAFKA_CLIENT_ID,
  AUTH_KAFKA_GROUP_ID: envVars.AUTH_KAFKA_GROUP_ID,
  AUTH_KAFKA_CLIENT: envVars.AUTH_KAFKA_CLIENT || 'AUTH_KAFKA_CLIENT',
  QRCODE_KAFKA_CLIENT_ID: envVars.QRCODE_KAFKA_CLIENT_ID,
  QRCODE_KAFKA_GROUP_ID: envVars.QRCODE_KAFKA_GROUP_ID,
  QRCODE_KAFKA_CLIENT: envVars.QRCODE_KAFKA_CLIENT || 'QRCODE_KAFKA_CLIENT',
  READINGS_KAFKA_CLIENT_ID: envVars.READINGS_KAFKA_CLIENT_ID,
  READINGS_KAFKA_GROUP_ID: envVars.READINGS_KAFKA_GROUP_ID,
  READINGS_KAFKA_CLIENT:
    envVars.READINGS_KAFKA_CLIENT || 'READINGS_KAFKA_CLIENT',
  QRCODE_SCANNER_KAFKA_GROUP_ID: envVars.QRCODE_SCANNER_KAFKA_GROUP_ID,
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID:
    envVars.EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID,
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID:
    envVars.EPAA_LEGACY_READINGS_KAFKA_GROUP_ID,
  EPAA_LEGACY_READINGS_KAFKA_CLIENT:
    envVars.EPAA_LEGACY_READINGS_KAFKA_CLIENT ||
    'EPAA_LEGACY_READINGS_KAFKA_CLIENT',
  OBSERVATION_KAFKA_GROUP_ID: envVars.OBSERVATION_KAFKA_GROUP_ID,
  OBSERVATION_KAFKA_CLIENT:
    envVars.OBSERVATION_KAFKA_CLIENT || 'OBSERVATION_KAFKA_CLIENT',
  OBSERVATION_KAFKA_CLIENT_ID:
    envVars.OBSERVATION_KAFKA_CLIENT_ID || 'observation-client',
  PHOTO_READING_KAFKA_GROUP_ID: envVars.PHOTO_READING_KAFKA_GROUP_ID,
  PHOTO_READING_KAFKA_CLIENT:
    envVars.PHOTO_READING_KAFKA_CLIENT || 'PHOTO_READING_KAFKA_CLIENT',
  PHOTO_READING_KAFKA_CLIENT_ID:
    envVars.PHOTO_READING_KAFKA_CLIENT_ID || 'PHOTO_READING_KAFKA_CLIENT_ID',
  LOCATION_CONNECTION_KAFKA_CLIENT_ID:
    envVars.LOCATION_CONNECTION_KAFKA_CLIENT_ID,
  LOCATION_CONNECTION_KAFKA_GROUP_ID:
    envVars.LOCATION_CONNECTION_KAFKA_GROUP_ID,
  LOCATION_CONNECTION_KAFKA_CLIENT:
    envVars.LOCATION_CONNECTION_KAFKA_CLIENT || 'LOCATION_KAFKA_CLIENT',
  LOCATION_KAFKA_CLIENT_ID:
    envVars.LOCATION_CONNECTION_KAFKA_CLIENT_ID || 'location-client',
  LOCATION_KAFKA_GROUP_ID:
    envVars.LOCATION_CONNECTION_KAFKA_GROUP_ID || 'location-group',
  LOCATION_KAFKA_CLIENT:
    envVars.LOCATION_CONNECTION_KAFKA_CLIENT || 'LOCATION_KAFKA_CLIENT',
  CLIENTS_KAFKA_CLIENT_ID: envVars.CLIENTS_KAFKA_CLIENT_ID,
  CLIENTS_KAFKA_GROUP_ID: envVars.CLIENTS_KAFKA_GROUP_ID,
  CLIENTS_KAFKA_CLIENT: envVars.CLIENTS_KAFKA_CLIENT || 'CLIENTS_KAFKA_CLIENT',
  COMPANIES_KAFKA_GROUP_ID:
    envVars.COMPANIES_KAFKA_GROUP_ID || 'companies-group',
  COMPANIES_KAFKA_CLIENT:
    envVars.COMPANIES_KAFKA_CLIENT || 'COMPANIES_KAFKA_CLIENT',
  COMPANIES_KAFKA_CLIENT_ID:
    envVars.COMPANIES_KAFKA_CLIENT_ID || 'companies-client',
  CONNECTION_KAFKA_GROUP_ID: envVars.CONNECTION_KAFKA_GROUP_ID,
  CONNECTION_KAFKA_CLIENT:
    envVars.CONNECTION_KAFKA_CLIENT || 'CONNECTION_KAFKA_CLIENT',
  CONNECTION_KAFKA_CLIENT_ID: envVars.CONNECTION_KAFKA_CLIENT_ID,
  PROPERTY_KAFKA_GROUP_ID: envVars.PROPERTY_KAFKA_GROUP_ID,
  PROPERTY_KAFKA_CLIENT:
    envVars.PROPERTY_KAFKA_CLIENT || 'PROPERTY_KAFKA_CLIENT',
  PROPERTY_KAFKA_CLIENT_ID: envVars.PROPERTY_KAFKA_CLIENT_ID,
  OBSERVATION_CONNECTION_KAFKA_GROUP_ID:
    envVars.OBSERVATION_CONNECTION_KAFKA_GROUP_ID,
  OBSERVATION_CONNECTION_KAFKA_CLIENT:
    envVars.OBSERVATION_CONNECTION_KAFKA_CLIENT,
  OBSERVATION_CONNECTION_KAFKA_CLIENT_ID:
    envVars.OBSERVATION_CONNECTION_KAFKA_CLIENT_ID,
  PHOTO_CONNECTION_KAFKA_GROUP_ID: envVars.PHOTO_CONNECTION_KAFKA_GROUP_ID,
  PHOTO_CONNECTION_KAFKA_CLIENT: envVars.PHOTO_CONNECTION_KAFKA_CLIENT,
  PHOTO_CONNECTION_KAFKA_CLIENT_ID: envVars.PHOTO_CONNECTION_KAFKA_CLIENT_ID,

  // Work Orders Kafka
  GATEWAY_WORK_ORDER_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_ORDER_KAFKA_CLIENT ||
    'GATEWAY_WORK_ORDER_KAFKA_CLIENT',
  GATEWAY_WORK_ORDER_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_ORDER_KAFKA_CLIENT_ID || 'work-order-gateway-client',
  GATEWAY_WORK_ORDER_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_ORDER_KAFKA_GROUP_ID || 'work-order-gateway-group',
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT ||
    'GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT',
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_ORDER_HISTORY_KAFKA_CLIENT_ID ||
    'work-order-history-gateway-client',
  GATEWAY_WORK_ORDER_HISTORY_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_ORDER_HISTORY_KAFKA_GROUP_ID ||
    'work-order-history-gateway-group',
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT ||
    'GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT',
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_CLIENT_ID ||
    'work-order-observation-gateway-client',
  GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_ORDER_OBSERVATION_KAFKA_GROUP_ID ||
    'work-order-observation-gateway-group',
  GATEWAY_WORK_TYPE_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_TYPE_KAFKA_CLIENT || 'GATEWAY_WORK_TYPE_KAFKA_CLIENT',
  GATEWAY_WORK_TYPE_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_TYPE_KAFKA_CLIENT_ID || 'work-type-gateway-client',
  GATEWAY_WORK_TYPE_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_TYPE_KAFKA_GROUP_ID || 'work-type-gateway-group',
  GATEWAY_WORKERS_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORKERS_KAFKA_GROUP_ID || 'workers-gateway-group',
  GATEWAY_WORKERS_KAFKA_CLIENT:
    envVars.GATEWAY_WORKERS_KAFKA_CLIENT || 'GATEWAY_WORKERS_KAFKA_CLIENT',
  GATEWAY_WORKERS_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORKERS_KAFKA_CLIENT_ID || 'workers-gateway-client',
  INVENTORY_KAFKA_CLIENT_ID:
    envVars.INVENTORY_KAFKA_CLIENT_ID || 'inventory-gateway-client',
  INVENTORY_KAFKA_GROUP_ID:
    envVars.INVENTORY_KAFKA_GROUP_ID || 'inventory-gateway-group',
  INVENTORY_KAFKA_CLIENT:
    envVars.INVENTORY_KAFKA_CLIENT || 'INVENTORY_KAFKA_CLIENT',
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_GROUP_ID:
    envVars.GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_GROUP_ID ||
    'detail-material-gateway-group',
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT:
    envVars.GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT ||
    'GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT',
  GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT_ID:
    envVars.GATEWAY_DETAIL_WORK_ORDER_MATERIAL_KAFKA_CLIENT_ID ||
    'detail-material-gateway-client',
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_GROUP_ID ||
    'worker-assignment-gateway-group',
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT ||
    'GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT',
  GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_ORDER_WORKER_ASSIGNMENT_KAFKA_CLIENT_ID ||
    'worker-assignment-gateway-client',
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_GROUP_ID:
    envVars.GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_GROUP_ID ||
    'attachments-gateway-group',
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT:
    envVars.GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT ||
    'GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT',
  GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT_ID:
    envVars.GATEWAY_WORK_ORDER_ATTACHMENTS_KAFKA_CLIENT_ID ||
    'attachments-gateway-client',

  // Auth & Security Kafka
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT:
    envVars.GATEWAY_AUTHENTICATION_KAFKA_CLIENT ||
    'GATEWAY_AUTHENTICATION_KAFKA_CLIENT',
  GATEWAY_AUTHENTICATION_KAFKA_CLIENT_ID:
    envVars.GATEWAY_AUTHENTICATION_KAFKA_CLIENT_ID || 'auth-gateway-client',
  GATEWAY_AUTHENTICATION_KAFKA_GROUP_ID:
    envVars.GATEWAY_AUTHENTICATION_KAFKA_GROUP_ID || 'auth-gateway-group',
  GATEWAY_ROLES_KAFKA_CLIENT:
    envVars.GATEWAY_ROLES_KAFKA_CLIENT || 'GATEWAY_ROLES_KAFKA_CLIENT',
  GATEWAY_ROLES_KAFKA_CLIENT_ID:
    envVars.GATEWAY_ROLES_KAFKA_CLIENT_ID || 'roles-gateway-client',
  GATEWAY_ROLES_KAFKA_GROUP_ID:
    envVars.GATEWAY_ROLES_KAFKA_GROUP_ID || 'roles-gateway-group',
  GATEWAY_CATEGORIES_KAFKA_CLIENT:
    envVars.GATEWAY_CATEGORIES_KAFKA_CLIENT ||
    'GATEWAY_CATEGORIES_KAFKA_CLIENT',
  GATEWAY_CATEGORIES_KAFKA_CLIENT_ID:
    envVars.GATEWAY_CATEGORIES_KAFKA_CLIENT_ID || 'categories-gateway-client',
  GATEWAY_CATEGORIES_KAFKA_GROUP_ID:
    envVars.GATEWAY_CATEGORIES_KAFKA_GROUP_ID || 'categories-gateway-group',
  GATEWAY_PERMISSIONS_KAFKA_CLIENT:
    envVars.GATEWAY_PERMISSIONS_KAFKA_CLIENT ||
    'GATEWAY_PERMISSIONS_KAFKA_CLIENT',
  GATEWAY_PERMISSIONS_KAFKA_CLIENT_ID:
    envVars.GATEWAY_PERMISSIONS_KAFKA_CLIENT_ID || 'permissions-gateway-client',
  GATEWAY_PERMISSIONS_KAFKA_GROUP_ID:
    envVars.GATEWAY_PERMISSIONS_KAFKA_GROUP_ID || 'permissions-gateway-group',
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT:
    envVars.GATEWAY_ROL_PERMISSION_KAFKA_CLIENT ||
    'GATEWAY_ROL_PERMISSION_KAFKA_CLIENT',
  GATEWAY_ROL_PERMISSION_KAFKA_CLIENT_ID:
    envVars.GATEWAY_ROL_PERMISSION_KAFKA_CLIENT_ID ||
    'rol-permission-gateway-client',
  GATEWAY_ROL_PERMISSION_KAFKA_GROUP_ID:
    envVars.GATEWAY_ROL_PERMISSION_KAFKA_GROUP_ID ||
    'rol-permission-gateway-group',
  GATEWAY_USERS_KAFKA_CLIENT:
    envVars.GATEWAY_USERS_KAFKA_CLIENT || 'GATEWAY_USERS_KAFKA_CLIENT',
  GATEWAY_USERS_KAFKA_CLIENT_ID:
    envVars.GATEWAY_USERS_KAFKA_CLIENT_ID || 'users-gateway-client',
  GATEWAY_USERS_KAFKA_GROUP_ID:
    envVars.GATEWAY_USERS_KAFKA_GROUP_ID || 'users-gateway-group',
  GATEWAY_EMPLOYEES_KAFKA_CLIENT:
    envVars.GATEWAY_EMPLOYEES_KAFKA_CLIENT || 'GATEWAY_EMPLOYEES_KAFKA_CLIENT',
  GATEWAY_EMPLOYEES_KAFKA_CLIENT_ID:
    envVars.GATEWAY_EMPLOYEES_KAFKA_CLIENT_ID || 'employees-gateway-client',
  GATEWAY_EMPLOYEES_KAFKA_GROUP_ID:
    envVars.GATEWAY_EMPLOYEES_KAFKA_GROUP_ID || 'employees-gateway-group',
  GATEWAY_AUTH_KAFKA_CLIENT:
    envVars.GATEWAY_AUTH_KAFKA_CLIENT || 'GATEWAY_AUTH_KAFKA_CLIENT',
  GATEWAY_AUTH_KAFKA_CLIENT_ID:
    envVars.GATEWAY_AUTH_KAFKA_CLIENT_ID || 'auth-client-gateway-client',
  GATEWAY_AUTH_KAFKA_GROUP_ID:
    envVars.GATEWAY_AUTH_KAFKA_GROUP_ID || 'auth-client-gateway-group',
  GATEWAY_LOCATION_KAFKA_CLIENT:
    envVars.GATEWAY_LOCATION_KAFKA_CLIENT || 'GATEWAY_LOCATION_KAFKA_CLIENT',
  GATEWAY_LOCATION_KAFKA_CLIENT_ID:
    envVars.GATEWAY_LOCATION_KAFKA_CLIENT_ID || 'location-gateway-client',
  GATEWAY_LOCATION_KAFKA_GROUP_ID:
    envVars.GATEWAY_LOCATION_KAFKA_GROUP_ID || 'location-gateway-group',

  // Trash Rate Kafka clients
  TRASH_RATE_KAFKA_CLIENT_ID: envVars.TRASH_RATE_KAFKA_CLIENT_ID,
  TRASH_RATE_KAFKA_CLIENT: envVars.TRASH_RATE_KAFKA_CLIENT,
  TRASH_RATE_KAFKA_GROUP_ID: envVars.TRASH_RATE_KAFKA_GROUP_ID,

  // Documents Service Kafka clients
  GATEWAY_DOCUMENTS_KAFKA_CLIENT: envVars.GATEWAY_DOCUMENTS_KAFKA_CLIENT,
  GATEWAY_DOCUMENTS_KAFKA_CLIENT_ID: envVars.GATEWAY_DOCUMENTS_KAFKA_CLIENT_ID,
  GATEWAY_DOCUMENTS_KAFKA_GROUP_ID: envVars.GATEWAY_DOCUMENTS_KAFKA_GROUP_ID,
  CONNECTION_DOCUMENTS_UPLOAD_DIR: envVars.CONNECTION_DOCUMENTS_UPLOAD_DIR,

  // JWT & Storage
  JWT_SECRET: envVars.JWT_SECRET,
  JWT_ACCESS_TOKEN_SECRET:
    envVars.JWT_SECRET || envVars.JWT_ACCESS_TOKEN_SECRET || 'epaa-secret-key',
  JWT_ACCESS_EXPIRATION: envVars.JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_EXPIRATION: envVars.JWT_REFRESH_EXPIRATION,
  FILE_STORAGE_PATH: envVars.FILE_STORAGE_PATH,
};
