import 'dotenv/config';
import * as Joi from 'joi';

interface EnvironmentVariables {
  NODE_ENV: 'development' | 'production' | 'test' | 'provision';
  PORT_DEVELOPMENT: number;
  PORT_PRODUCTION: number;
  AUTH_MICROSERVICE_HOST: string;
  AUTH_MICROSERVICE_PORT: number;
  AUTH_SERVICE: string;
  QR_CODE_MICROSERVICE_HOST: string;
  QR_CODE_MICROSERVICE_PORT: number;
  QR_CODE_SERVICE: string;
  READINGS_MICROSERVICE_HOST: string;
  READINGS_MICROSERVICE_PORT: number;
  READINGS_SERVICE: string;
  KAFKA_BROKER_URL: string;
  AUTH_KAFKA_CLIENT_ID: string;
  AUTH_KAFKA_GROUP_ID: string;
  AUTH_KAFKA_CLIENT: string;
  QRCODE_KAFKA_CLIENT_ID: string;
  QRCODE_KAFKA_GROUP_ID: string;
  QRCODE_KAFKA_CLIENT: string;
  READINGS_KAFKA_CLIENT_ID: string;
  READINGS_KAFKA_GROUP_ID: string;
  READINGS_KAFKA_CLIENT: string;
  QRCODE_SCANNER_KAFKA_GROUP_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID: string;
  EPAA_LEGACY_READINGS_KAFKA_CLIENT: string;
}

const envVarsSchema: Joi.ObjectSchema<EnvironmentVariables> = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test', 'provision')
    .default('development'),
  PORT_DEVELOPMENT: Joi.number(),
  PORT_PRODUCTION: Joi.number(),
  AUTH_MICROSERVICE_HOST: Joi.string(),
  AUTH_MICROSERVICE_PORT: Joi.number(),
  AUTH_SERVICE: Joi.string(),
  QR_CODE_MICROSERVICE_HOST: Joi.string(),
  QR_CODE_MICROSERVICE_PORT: Joi.number(),
  QR_CODE_SERVICE: Joi.string(),
  READINGS_MICROSERVICE_HOST: Joi.string(),
  READINGS_MICROSERVICE_PORT: Joi.number(),
  READINGS_SERVICE: Joi.string(),
  KAFKA_BROKER_URL: Joi.string(),
  AUTH_KAFKA_CLIENT_ID: Joi.string(),
  AUTH_KAFKA_GROUP_ID: Joi.string(),
  AUTH_KAFKA_CLIENT: Joi.string(),
  QRCODE_KAFKA_CLIENT_ID: Joi.string(),
  QRCODE_KAFKA_GROUP_ID: Joi.string(),
  QRCODE_KAFKA_CLIENT: Joi.string(),
  READINGS_KAFKA_CLIENT_ID: Joi.string(),
  READINGS_KAFKA_GROUP_ID: Joi.string(),
  READINGS_KAFKA_CLIENT: Joi.string(),
  QRCODE_SCANNER_KAFKA_GROUP_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID: Joi.string(),
  EPAA_LEGACY_READINGS_KAFKA_CLIENT: Joi.string(),
}).unknown();

const { error, value: envVars } = envVarsSchema.validate(process.env);

if (error) {
  throw new Error(`Config validation error: ${error.message}`);
}

export const environments = {
  NODE_ENV: envVars.NODE_ENV,
  PORT:
    envVars.NODE_ENV === 'production'
      ? envVars.PORT_PRODUCTION
      : envVars.PORT_DEVELOPMENT,
  AUTH_MICROSERVICE_HOST: envVars.AUTH_MICROSERVICE_HOST,
  AUTH_MICROSERVICE_PORT: envVars.AUTH_MICROSERVICE_PORT,
  AUTH_SERVICE: envVars.AUTH_SERVICE,
  QR_CODE_MICROSERVICE_HOST: envVars.QR_CODE_MICROSERVICE_HOST,
  QR_CODE_MICROSERVICE_PORT: envVars.QR_CODE_MICROSERVICE_PORT,
  QR_CODE_SERVICE: envVars.QR_CODE_SERVICE,
  READINGS_MICROSERVICE_HOST: envVars.READINGS_MICROSERVICE_HOST,
  READINGS_MICROSERVICE_PORT: envVars.READINGS_MICROSERVICE_PORT,
  READINGS_SERVICE: envVars.READINGS_SERVICE,
  KAFKA_BROKER_URL: envVars.KAFKA_BROKER_URL,
  AUTH_KAFKA_CLIENT_ID: envVars.AUTH_KAFKA_CLIENT_ID,
  AUTH_KAFKA_GROUP_ID: envVars.AUTH_KAFKA_GROUP_ID,
  AUTH_KAFKA_CLIENT: envVars.AUTH_KAFKA_CLIENT,
  QRCODE_KAFKA_CLIENT_ID: envVars.QRCODE_KAFKA_CLIENT_ID,
  QRCODE_KAFKA_GROUP_ID: envVars.QRCODE_KAFKA_GROUP_ID,
  QRCODE_KAFKA_CLIENT: envVars.QRCODE_KAFKA_CLIENT,
  READINGS_KAFKA_CLIENT_ID: envVars.READINGS_KAFKA_CLIENT_ID,
  READINGS_KAFKA_GROUP_ID: envVars.READINGS_KAFKA_GROUP_ID,
  READINGS_KAFKA_CLIENT: envVars.READINGS_KAFKA_CLIENT,
  QRCODE_SCANNER_KAFKA_GROUP_ID: envVars.QRCODE_SCANNER_KAFKA_GROUP_ID,
  EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID: envVars.EPAA_LEGACY_READINGS_KAFKA_CLIENT_ID,
  EPAA_LEGACY_READINGS_KAFKA_GROUP_ID: envVars.EPAA_LEGACY_READINGS_KAFKA_GROUP_ID,
  EPAA_LEGACY_READINGS_KAFKA_CLIENT: envVars.EPAA_LEGACY_READINGS_KAFKA_CLIENT,
};  